project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Final Project: Community Health Index"
  site-url: "https://musa-550-fall-2023.github.io/Tiffany_Final-Project-Template" 
  repo-url: https://github.com/MUSA-550-Fall-2023/Tiffany_Final-Project-Template 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Tiffany luo, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Overview
      - section: analysis/index.qmd
        contents:
          - analysis/Step1.ipynb
          - analysis/Step2.ipynb
          - analysis/Step3.ipynb
          - analysis/Step4.ipynb
          

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




