---
title: "Final Project: Community Health Index in Philadelphia"
subtitle: "Tiffany Luo"
---

## Overview

In this project, I am working with geospatial data related to community health and amenities. The analysis involves exploring parks, health centers, and perceived health levels in neighborhoods. Walkability analysis is conducted to assess the proximity of health centers and parks, contributing to the understanding of community health. Regression analysis is performed to identify correlations between the number of health centers, parks, and the percentage of adults reporting fair or poor health.

The creation of a Community Health Index is motivated by a desire to comprehensively assess community health. Inspired by the CDC's Social Vulnerability Index (SVI), this index combines variables such as the number of health centers, parks, and the percentage of residents reporting fair or poor health. I aim to create a holistic measure, akin to the SVI, to evaluate community health levels. The index involves normalizing and aggregating various factors, allowing for a nuanced understanding of vulnerability and health disparities within different neighborhoods.

The exploration of parks, health centers, and perceived health levels, coupled with walkability analysis, regression, and the creation of a Community Health Index, collectively contribute to a multidimensional assessment of community health and vulnerability. As result, I identified the neighborhoods in Philadelphia that most needs  public health strategies and interventions.



 
